<script src="{{ asset('/') }}frontEnd/assets/js/jquery-3.7.1.min.js"></script>
<script src="{{ asset('/') }}frontEnd/assets/js/plugins.js"></script>
<script src="{{ asset('/') }}frontEnd/assets/js/mdtimepicker.min.js"></script>
<!-- for calender  -->
<script src="{{ asset('/') }}frontEnd/assets/js/js-date-extensions.js"></script>
<script src="{{ asset('/') }}frontEnd/assets/js/jquery.bs.calendar.min.js"></script>
<script src="{{ asset('/') }}frontEnd/assets/js/calendar.js"></script>
<!-- main js  -->
<script src="{{ asset('/') }}frontEnd/assets/js/main.js"></script>
